# Generated by Django 4.2.3 on 2023-07-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_items_cart_item_id_remove_items_cart_items_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items_cart',
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart_items',
            name='varient',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
