# Generated by Django 4.2.3 on 2023-07-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='identify_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
